name: Gerar HTML Estático

on:
  workflow_dispatch:

jobs:
  gerar-html:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        npm install
        npm install -D ts-node typescript node-fetch @types/node

    - name: Rodar o script
      run: npx ts-node generateStaticPages.ts

    - name: Salvar artefatos (HTMLs gerados)
      uses: actions/upload-artifact@v3
      with:
        name: paginas-geradas
        path: dist/acompanhante
